version: '3'

services:
  web:
    build: .
    container_name: restFramework
    ports: 
      - 80:80
    volumes:
    - .:/app
    depends_on:
      - db
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
